version: '3'

services:
  webserver: 
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
        - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:password@mysql:3306
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bulletin_board_development
      MYSQL_USERNAME: root
    ports:
    - "4306:3306"
volumes:
  public-data:
  tmp-data:
  log-data:
  mysql_data: