version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Gemfile.lock" }}
            - v2-dependencies- 
      - run:
          name: Install Bundle
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
      - run:
          name: "before_test: setup db"
          command: docker-compose run webserver rails db:create db:migrate
      - run:
          name: test
          command: docker-compose run webserver bundle exec rspec
workflows:
  version: 2
  build:
    jobs:
      - build