version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers-legacy
    working_directory: ~/myapp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Gemfile.lock" }}
            - v2-dependencies- 
      - run:
          name: Install Bundle
          command: |
            gem install bundler -v 1.17.3
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run: gem install bundler
      - run:
          name: Run Rspec
          command: bundle exec rspec
